# Variable definitions
variables:
  RUN_PIPLINE:
    value: "true"  # run pipline NOT by default
    description: "Run the pipline if set to true."

  PROJECT_NAME:
    value: "opsi_quick_install_project"
    description: "Project name of the project the pipline should run on."

  BINARY_VERSION:
    value: "4.12.4.22"
    description: "Version of the binary"

  PLATFORM:
    value: "Linux"
    description: "For which build modes should the lazarus project be compiled?  
    all: build project for all platforms (Win32, Win64, Linux, MacOS)
    Windows (Linux, MacOS):  build project for the specified platform only"
  
# Control of the Pipline  
workflow:
  rules: 
    - if: '$RUN_PIPLINE == "true"' # && $CI_PIPELINE_SOURCE == "push"'
    # - if: '$CI_COMMIT_MESSAGE =~ /-compile$/ && $CI_PIPELINE_SOURCE == "push"'
      when: always

stages:
  - build
  - binaryindex

#***************************************#
#  opsi-script pipline                  #
#***************************************#

compile opsi-quickinstall linux:
  stage: build
  tags:
    - laz-linux
  variables:
    PROJECT_REPOSITORY_PATH: "opsi-misc/opsi-quickinstall"
  rules:
    - if: ($PROJECT_NAME == "opsi_quick_install_project" && $PLATFORM == "Linux") 
      when: always
  script: 
    - LAZ_PROJECT_FILE_GUI=${PROJECT_REPOSITORY_PATH}/gui/${PROJECT_NAME}.lpi
    - LAZ_PROJECT_FILE_NOGUI=${PROJECT_REPOSITORY_PATH}/nogui/${PROJECT_NAME}.lpi
    - echo "$LAZ_PROJECT_FILE"
    - echo "Compiling $PROJECT_NAME for Linux with no GUI"
    - /usr/bin/lazbuild $LAZ_PROJECT_FILE_NOGUI
    - echo "Compiling $PROJECT_NAME for Linux with GUI"
    - /usr/bin/lazbuild $LAZ_PROJECT_FILE_GUI
    #- cd opsi-misc/opsi-quickinstall/build/opsi-quickinstall/ &&
    # - $BINARY_OUT_PATH = $PROJECT_NAME -eq "opsiscript")
  artifacts:
    name: "opsi-quickinstall $BINARY_VERSION linux"
    paths:
      - opsi-misc/opsi-quickinstall/build/*

publish opsi-quick-install:
  stage: binaryindex
  tags:
    - laz-linux
  variables:
    PROJECT_REPOSITORY_PATH: "opsi-misc/opsi-quickinstall"
  rules:
    - if: ($PROJECT_NAME == "opsi_quick_install_project" && $PLATFORM == "Linux")
      when: always
  script:
    - cd opsi-misc/opsi-quickinstall/build/ && ./opsi-dev-tool --log-level info --uib-binaryindex-password=ahx9taePhu --binary-push opsi-quickinstall opsi-quick-install linux x64 4.2.0.0-0
