# Variable definitions
variables:
  RUN_PIPLINE:
    value: "false"  # run pipline NOT by default
    description: "Run the pipline if set to true."

  PROJECT_NAME:
    value: "opsiscript"
    description: "Project name of the project the pipline should run on."

  #PROJECT_REPOSITORY_PATH:
  #  value: "/opsi-script"
  #  description: "Path to the lazarus project within this git repository."

  PLATFORM:
    value: "all"
    description: "For which build modes should the lazarus project be compiled?  
    all: build project for all platforms (Win32, Win64, Linux, MacOS)
    Windows (Linux, MacOS):  build project for the specified platform only"
  
# Control of the Pipline  
workflow:
  rules: 
    - if: '$RUN_PIPLINE == "true"' # && $CI_PIPELINE_SOURCE == "push"'
    # - if: '$CI_COMMIT_MESSAGE =~ /-compile$/ && $CI_PIPELINE_SOURCE == "push"'
      when: always

stages:
  - build
#  - binaryindex

compile opsi-script windows:
  stage: build
  tags:
    - laz-win10
  variables:
    PROJECT_REPOSITORY_PATH: "opsi-script\\"
  rules:
    - if: ($PROJECT_NAME == "opsiscript") && ($PLATFORM == "all" || $PLATFORM == "Windows") 
      when: always
  script: 
    - $LAZ_PROJECT_FILE=Join-Path ${PROJECT_REPOSITORY_PATH}  "${PROJECT_NAME}.lpi"
    - echo "$LAZ_PROJECT_FILE"
    - echo "Compiling $PROJECT_NAME for Win32"
    - C:\lazarus\lazbuild.exe $LAZ_PROJECT_FILE --build-mode=Release_Win32
    - echo "Compiling $PROJECT_NAME for Win64"
    # - C:\lazarus\lazbuild.exe .$LAZ_PROJECT_FILE --build-mode=Release_Win64
    # - $BINARY_OUT_PATH = $PROJECT_NAME -eq "opsiscript")
  artifacts:
    name: opsi-script_Windows
    paths:
      - opsi-script\compiler_out\binarys\ #i386-win32\opsi-script.exe
      # - \opsi-script\compiler_out\binarys\x86_64-win64\opsi-script.exe



