# Variable definitions
variables:
  RUN_PIPLINE:
    value: "false"  # run pipline NOT by default
    description: "Run the pipline if set to true."

  PROJECT_NAME:
    value: "opsi-script"
    description: "Project name of the project the pipline should run on."

  LAZ_PROJECT_PATH:
    value: "/opsi-script"
    description: "Path to the lazarus project within this git repository."

  PROJECT_BUILD_MODE:
    value: "all"
    description: "For which build modes should the lazarus project be compiled?  
    all: build project for all platforms (Win32, Win64, Linux, MacOS) and variants (gui, nogui)
    Windows (Linux, MacOS):  build project for the specified platform only"
  
# Control of the Pipline  
workflow:
  rules: 
    - if: '$RUN_PIPLINE == "true"' # && $CI_PIPELINE_SOURCE == "push"'
    # - if: '$CI_COMMIT_MESSAGE =~ /-compile$/ && $CI_PIPELINE_SOURCE == "push"'
      when: always

stages:
  - build
#  - binaryindex

compile windows:
  stage: build
  tags:
    - laz-win10
  script: 
    - echo "CI-Path $CI_PROJECT_PATH"
    - echo "CI-Dir $CI_PROJECT_DIR"
    - echo "CI-Name $CI_PROJECT_NAME"
    - echo "Compiling $PROJECT_MANE for Win32"
    # - C:\lazarus\lazbuild.exe ${PROJECT_NAME}.lpi --lazarusdir=$LAZ_PROJECT_PATH --build-mode=Release_Win32
    - echo "Compiling $PROJECT_MANE for Win64"
    # - C:\lazarus\lazbuild.exe ${PROJECT_NAME}.lpi --lazarusdir=$LAZ_PROJECT_PATH --build-mode=Release_Win64

