////                                                            
; Copyright (c) uib gmbh (www.uib.de)                           
; This documentation is owned by uib                            
; and published under the german creative commons by-sa license 
; see:                                                          
; http://creativecommons.org/licenses/by-sa/3.0/de/             
; http://creativecommons.org/licenses/by-sa/3.0/de/legalcode    
; english:                                                      
; http://creativecommons.org/licenses/by-sa/3.0/                
; http://creativecommons.org/licenses/by-sa/3.0/legalcode       
;                                                               
;                          
////                                                            
                                                                
:Revision:                                                 
:doctype: book                                               
:Author:    detlef oertel
:Email:    d.oertel@uib.de
:toc:
   
   
   
[Doc_fileuib_backend.opsiscript]
= Documentation of opsi library: `uib_backend.opsiscript`



* Email:     d.oertel@uib.de
* Version:  1.0
* Copyright:  AGPLv3





anchor:setProductsToSetup[]
[Doc_func_setProductsToSetup]
== Documentation of local function `setProductsToSetup`


Definition::
`setProductsToSetup($productlist$ : stringlist) : string`

Description::
Sets for the given list of opsi productIds the action request
to 'setup' (also resolving the dependencies)

* Parameter: `$productlist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`
** Parameter `$productlist$` Description: +
List of opsi product Ids

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Works only in opsi service mode (not in interactive or batch mode)
* Author:     detlef oertel
* Date:     17.5.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


Example:
[source,winst]
----
[actions]
DefStringlist $productlist$

set $productlist$ = CreateStringList("opsi-logviewer","opsi-configed")
if not(stringtobool(setProductsToSetup($productlist$)))
  comment "call of setProductsToSetup failed"
endif
----



anchor:getInstalledLocalbootProducts[]
[Doc_func_getInstalledLocalbootProducts]
== Documentation of local function `getInstalledLocalbootProducts`


Definition::
`getInstalledLocalbootProducts(ref $productlist$ : stringlist) : string`

Description::
Sets for the given list of opsi productIds the action request
to 'setup' (also resolving the dependencies)

* Parameter: `$productlist$`
** Type: `Stringlist`  -  Calltype: `CallByReference`
** Parameter `$productlist$` Description: +
Output list of opsi product Ids that were be found
** Parameter `$productlist$` Advice: +
May be empty

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Works only in opsi service mode (not in interactive or batch mode)
* Author:     detlef oertel
* Date:     20.4.2018
* Email:     d.oertel@uib.de
* Version:     1.1
* Copyright:     AGPLv3



anchor:delOpsiPoc[]
[Doc_func_delOpsiPoc]
== Documentation of local function `delOpsiPoc`


Definition::
`delOpsiPoc($donotdelList$ : stringlist) : string`

Description::
Delete all productOnClientObjects for this client and
only for localboot products and
not for products that are included in the $donotdelList$ parameter

* Parameter: `$donotdellist$`
** Type: `Stringlist`  -  Calltype: `CallByValue`

* Returns:     Returns string "true" if all is ok
* OnError:     Returns string "false"
* SpecialCase:     Works only in opsi service mode (not in interactive or batch mode)
* Author:     detlef oertel
* Date:     17.4.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:backupOpsiPoc[]
[Doc_func_backupOpsiPoc]
== Documentation of local function `backupOpsiPoc`


Definition::
`backupOpsiPoc($filename$ : string) : string`

Description::


* Parameter: `$filename$`
** Type: `String`  -  Calltype: `CallByValue`

* Author:     detlef oertel
* Date:     17.4.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:restoreOpsiPoc[]
[Doc_func_restoreOpsiPoc]
== Documentation of local function `restoreOpsiPoc`


Definition::
`restoreOpsiPoc($filename$ : string) : string`

Description::


* Parameter: `$filename$`
** Type: `String`  -  Calltype: `CallByValue`

* Author:     detlef oertel
* Date:     17.4.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:getInstalledLocalbootProductsWithVersion[]
[Doc_func_getInstalledLocalbootProductsWithVersion]
== Documentation of local function `getInstalledLocalbootProductsWithVersion`


Definition::
`getInstalledLocalbootProductsWithVersion(ref $productlist$ : stringlist) : string`

Description::


* Parameter: `$productlist$`
** Type: `Stringlist`  -  Calltype: `CallByReference`

* Author:     detlef oertel
* Date:     17.4.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3



anchor:getInstallableLocalbootProductsWithVersion[]
[Doc_func_getInstallableLocalbootProductsWithVersion]
== Documentation of local function `getInstallableLocalbootProductsWithVersion`


Definition::
`getInstallableLocalbootProductsWithVersion(ref $productlist$ : stringlist) : string`

Description::


* Parameter: `$productlist$`
** Type: `Stringlist`  -  Calltype: `CallByReference`

* Author:     detlef oertel
* Date:     17.4.2018
* Email:     d.oertel@uib.de
* Version:     1.0
* Copyright:     AGPLv3


